import type { Meta, StoryObj } from "@storybook/react-vite";
const copy = {
 en: {title:"Export Data",intro:"Save a backup, a readable Excel file, or an AI review file.",policy:"Android cloud backup is disabled for Smart Paper. Device-to-device transfer may be available, depending on your Android version and devices. Save a JSON backup outside the app and check the file before changing phones or uninstalling.",safety:"The JSON backup is not encrypted. Save it outside this app and check the file before replacing data or uninstalling.",locked:"Finance Is Locked",pin:"Finance PIN",unlock:"Unlock Export",notice:"On Android, the PIN only hides this screen. Finance data is not encrypted. Finance locks again when the app reloads or restarts, including after a device transfer.",backup:"Export JSON Backup",restore:"Choose JSON Backup",report:"AI report",reportInfo:"Choose details for a separate Markdown report. This is not a restorable backup."},
 fa: {title:"خروجی داده‌ها",intro:"یک پشتیبان، فایل خوانای اکسل، یا فایل بررسی با هوش مصنوعی ذخیره کنید.",policy:"پشتیبان‌گیری ابری اندروید برای اسمارت پیپر غیرفعال است. انتقال مستقیم بین دستگاه‌ها ممکن است بسته به نسخه اندروید و دستگاه‌های شما در دسترس باشد. پیش از تعویض گوشی یا حذف برنامه، یک پشتیبان JSON بیرون از برنامه ذخیره و فایل را بررسی کنید.",safety:"فایل پشتیبان JSON رمزگذاری نشده است. آن را بیرون از برنامه ذخیره و بررسی کنید؛ سپس داده‌ها را جایگزین یا برنامه را حذف کنید.",locked:"بخش مالی قفل است",pin:"رمز بخش مالی",unlock:"باز کردن خروجی",notice:"در اندروید، رمز فقط این صفحه را پنهان می‌کند. داده‌های مالی رمزگذاری نشده‌اند. با بارگذاری دوباره یا اجرای مجدد برنامه، از جمله پس از انتقال به دستگاه دیگر، بخش مالی دوباره قفل می‌شود.",backup:"پشتیبان JSON",restore:"انتخاب فایل پشتیبان JSON",report:"گزارش هوش مصنوعی",reportInfo:"جزئیات را برای یک گزارش جداگانه Markdown انتخاب کنید. این گزارش فایل پشتیبان قابل بازیابی نیست."},
};
function AndroidBackupPolicy({language="both",theme="light",width="phone",state="locked"}:{language?:"both"|"en"|"fa";theme?:"light"|"dark";width?:"phone"|"wide";state?:"locked"|"unlocked"}) {
 const languages=language==="both"?["en","fa"] as const:[language];const dark=theme==="dark";const warning=dark?"#f5d494":"#78350f";
 return <main className={`studio-board ${dark?"studio-board-dark":""}`}><div className="studio-heading"><h1>Android backup policy · Export disclosure</h1><p>Proposal with existing Export hierarchy; report controls summarized. No promised OS transfer success.</p></div><div className={`studio-pair ${width==="wide"?"wide":""}`}>
 {languages.map(lang=>{const t=copy[lang];return <article key={lang} className={`phone ${width==="wide"?"wide":""} ${dark?"theme-dark":""}`} lang={lang} dir={lang==="fa"?"rtl":"ltr"} style={{padding:16,minHeight:0}}>
 <section className="box"><h1 style={{fontSize:30,margin:0}}>{t.title}</h1><p>{t.intro}</p><p style={{color:warning,fontSize:14,lineHeight:1.65}}>{t.safety}</p><p style={{color:warning,fontSize:14,lineHeight:1.65}}>{t.policy}</p></section>
 <section className="box"><h2>{t.report}</h2><p>{t.reportInfo}</p></section>
 {state==="locked"?<section className="box"><label style={{display:"block"}}>{t.pin}<input type="password" aria-label={t.pin} style={{display:"block",width:"100%",minHeight:48,margin:"8px 0",border:"1px solid #8b784c",borderRadius:8,background:dark?"#1b2b29":"#fff",color:dark?"#eef5f1":"#172b29"}}/></label><button className="btn" style={{minHeight:48}}>{t.unlock}</button></section>:<section className="box"><button className="btn" style={{minHeight:48}}>{t.backup}</button><h2>{lang==="fa"?"ورود داده‌ها":"Import Data"}</h2><p>{lang==="fa"?"ادغام / به‌روزرسانی":"Merge / upsert"}</p><button className="btn alt" style={{minHeight:48}}>{t.restore}</button></section>}
 </article>;})}</div><p className="studio-note">Disclosure precedes unlock. Static proposal; native restore and lifecycle need separate verification.</p></main>;
}
const meta={title:"Proposals/Android backup policy",component:AndroidBackupPolicy,args:{language:"both",theme:"light",width:"phone",state:"locked"},argTypes:{language:{control:"radio",options:["both","en","fa"]},theme:{control:"radio",options:["light","dark"]},width:{control:"radio",options:["phone","wide"]},state:{control:"radio",options:["locked","unlocked"]}}} satisfies Meta<typeof AndroidBackupPolicy>;
export default meta;type Story=StoryObj<typeof meta>;
export const LockedPhone:Story={};export const UnlockedPhone:Story={args:{state:"unlocked"}};export const DarkPhone:Story={args:{theme:"dark"}};export const Wide:Story={args:{width:"wide"}};export const DarkWide:Story={args:{width:"wide",theme:"dark",state:"unlocked"}};
